version: '3'

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=127.0.0.1
            - DB_PORT=3306
            - DB_DATABASE=brewdog
            - DB_USERNAME=root
            - DB_PASSWORD=
